### PR TITLE
Introduce Java wrappers for Bigchain DB Endpoints

### PR DESCRIPTION
**Pull request by alvin-reyes**
+ Configuration Builder to quickly create new instance of connection.
+ Introduce Model/Pojos
+ Model Api to expose the HTTP Endpoint functions of the available operations
+ Added GSON as part of the initiative to move away from org.json.
+ Re-created the makeSortedList algorithm to recurse through all the available maps regardless of the structure depth
+ Modified readme.md to reflect the changes.

### CODE REVIEW

**Comment by alvin-reyes** [comment]
@bodia , @tzclucian - let me know your thoughts.

**Comment by bodia** [comment]
Sorry for the late reply, haven't the time to review the changes earlier, they look good. There are a couple of tweaks I would add, but they are the minor ones.

**Comment by tzclucian** [comment]
Amazing progress @alvin-reyes .

Same notes as @bodia added. I saw some minor tweaks (e.g. the timeout configs could be moved to `Globals` or given as parameters) but considering this is WIP we will get there eventually.

On a side note I was thinking that the builders got a little too complicated maybe?
Also it seems to me that we're digging through JSONs a little bit too much and we should rely more on POJOs and maybe generics in the future?

Nonetheless, amazing work.
Thank you!

**Comment by bodia** [comment]
I've also noticed it's not possible to have an unsigned transaction currently. I have a usecase for this within my project.

**Comment by alvin-reyes** [comment]
I'll create issues for the comments here. Thank you for your feedback. I'll definitely accommodate them.

**Pull request merged**
